### PR TITLE
display map on website and other features, AddRoom feature

### PR DESCRIPTION
**Pull request by femybiju**
creating the pull request to merge code of displaying the map on the website and adding interactive features into the development

### CODE REVIEW

**Review by arpandeep — APPROVED** [review]
the code with map addition works fine without code conflict

**Review by GURUCHARAN23 — APPROVED** [review]
Map is getting displayed correctly with zoom in and out , search functionality.

**Comment by SaiVenu1018** [comment]
The code works fine

**Review by SaiVenu1018 — APPROVED** [review]
Your code working fine

**Pull request merged**
